
language: node_js
node_js:
  - '8'
  - '10'
  - '11'
  - '14'
  - '16'
before_install:
  - npm i npminstall@5 -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
